module Mobility
  module Sequel
=begin

Module included in price class dynamically generated by
{Backends::Sequel::Table} backend.

=end
    module ModelPrice
      def self.included(base)
        base.plugin :validation_helpers
      end

      def validate
        super
        validates_presence [:currency]
      end
    end
  end
end
